### ISSUE TITLE
Hook error if two apps with same name are related via CMR

### ISSUE THREAD

**Issue by johnsca** [openstack-charmers/charm-interface-vault-kv#12]
I think there's a conflict in the key the interface layer is choosing to identify the secrets backend for the requester.  If you have one app related and working, then via CMR relate another app with the same name, the second one goes to working but with has the secrets from the first app and the first app subsequently breaks with:

```python-traceback
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-vk-test-0/.venv/lib/python3.8/site-packages/charms/reactive/__init__.py", line 73, in main
    hookenv._run_atstart()
  File "/var/lib/juju/agents/unit-vk-test-0/.venv/lib/python3.8/site-packages/charmhelpers/core/hookenv.py", line 1334, in _run_atstart
    callback(*args, **kwargs)
  File "/var/lib/juju/agents/unit-vk-test-0/charm/reactive/vault_kv.py", line 48, in manage_app_kv_flags
    app_kv = vault_kv.VaultAppKV()
  File "lib/charms/layer/vault_kv.py", line 30, in __call__
    cls._singleton_instance = super().__call__(*args, **kwargs)
  File "lib/charms/layer/vault_kv.py", line 117, in __init__
    super().__init__()
  File "lib/charms/layer/vault_kv.py", line 38, in __init__
    response = self._client.read(self._path)
  File "lib/charms/layer/vault_kv.py", line 54, in _client
    client.auth_approle(self._config['role_id'], self._config['secret_id'])
  File "/var/lib/juju/agents/unit-vk-test-0/.venv/lib/python3.8/site-packages/hvac/v1/__init__.py", line 1523, in auth_approle
    return self.login('/v1/auth/{0}/login'.format(mount_point), json=params, use_token=use_token)
  File "/var/lib/juju/agents/unit-vk-test-0/.venv/lib/python3.8/site-packages/hvac/v1/__init__.py", line 1276, in login
    return self._adapter.login(
  File "/var/lib/juju/agents/unit-vk-test-0/.venv/lib/python3.8/site-packages/hvac/adapters.py", line 178, in login
    response = self.post(url, **kwargs)
  File "/var/lib/juju/agents/unit-vk-test-0/.venv/lib/python3.8/site-packages/hvac/adapters.py", line 107, in post
    return self.request('post', url, **kwargs)
  File "/var/lib/juju/agents/unit-vk-test-0/.venv/lib/python3.8/site-packages/hvac/adapters.py", line 342, in request
    response = super(JSONAdapter, self).request(*args, **kwargs)
  File "/var/lib/juju/agents/unit-vk-test-0/.venv/lib/python3.8/site-packages/hvac/adapters.py", line 304, in request
    utils.raise_for_error(
  File "/var/lib/juju/agents/unit-vk-test-0/.venv/lib/python3.8/site-packages/hvac/utils.py", line 47, in raise_for_error
    raise exceptions.InternalServerError(message, errors=errors, method=method, url=url)
hvac.exceptions.InternalServerError: failed to verify subset relationship between CIDR blocks on the role ["10.146.199.80/32"] and CIDR blocks on the secret ID ["10.146.199.221/32"]: <nil>, on post http://10.146.199.125:8200/v1/auth/approle/login
```

**Comment by kwmonroe** [comment]
Fixed in #14
